<div class="col-md-9">
    <h3>Resources / CPA Connect</h3>
    <hr>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a maximus risus, id rutrum orci. Pellentesque vel massa at magna luctus faucibus ut quis sapien. Sed faucibus vehicula ligula, vitae tincidunt dolor lobortis ut. Suspendisse ut convallis dolor. Sed venenatis magna libero, nec interdum felis rutrum ac. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut elementum elit ut nunc rhoncus congue. Maecenas maximus scelerisque leo ut facilisis. Nulla vestibulum ornare pharetra. Duis rutrum tortor euismod feugiat sodales. Integer sit amet lorem sed dolor vehicula facilisis vel eget mi. Praesent a ante non nulla venenatis lacinia sit amet in dolor. Morbi eget feugiat magna. Vestibulum ac dui vitae leo condimentum hendrerit ac at nulla.
        <br><br>
        Aenean sed mauris quis eros finibus rutrum. Nam et aliquet metus, eu blandit tortor. Donec nec ultrices nisi. Nam ultricies erat vel purus ultrices vehicula. Donec mauris nibh, fermentum et interdum faucibus, luctus ac justo. Etiam rutrum velit ut arcu porttitor dapibus. Morbi finibus urna vitae sollicitudin scelerisque.
        <br><br>
        Aenean sapien purus, consequat non lectus non, viverra dignissim felis. Integer augue tortor, placerat sed sodales ut, efficitur id lacus. Donec porttitor semper nisl et eleifend. Phasellus turpis ligula, molestie id arcu at, scelerisque convallis magna. Phasellus sit amet dignissim risus, sit amet laoreet nisi. Proin dictum quis diam vel tincidunt. Donec pretium nisl quis massa consectetur, vel ornare ligula commodo. Maecenas sagittis risus nec nibh blandit cursus. Quisque id velit ut metus efficitur dignissim et sed velit. Fusce id diam at lacus interdum dapibus in eu neque. Ut porta ipsum lorem, in rutrum nulla pretium et. Curabitur non sem condimentum, laoreet mi quis, ultrices ante. Aenean lobortis tristique elit, et mattis turpis tristique congue.
        <br><br>
        Suspendisse ut suscipit sapien. Nunc at blandit lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur et pulvinar elit. Vestibulum a varius neque. Sed sem nisl, ultricies consectetur faucibus gravida, rutrum vitae purus. Pellentesque placerat neque vel orci tincidunt egestas. Duis egestas nec nibh vitae dignissim. Etiam faucibus posuere faucibus. Donec id dignissim felis.
        <br><br>
        Duis et porta augue. Curabitur et augue auctor ipsum finibus faucibus. Nam vitae dictum nisl. Morbi blandit libero eu massa iaculis, at auctor massa rutrum. Phasellus condimentum ex nec elementum pellentesque. Vestibulum consequat odio augue, nec eleifend erat pharetra non. Donec venenatis lorem in ligula ultricies feugiat sed id velit. Donec venenatis ipsum eu diam rhoncus tristique. Cras tincidunt ac mi eu pellentesque. Quisque a vestibulum odio. Phasellus sodales, elit eu ullamcorper malesuada, purus justo posuere mauris, vitae eleifend velit massa sit amet neque. Aenean gravida velit id augue facilisis dapibus.
    </p>
</div>